# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'pure1/go.mod'
          cache-dependency-path: pure1/go.sum

      - name: Build
        run: cd pure1 && go build -v ./...

      - name: Test
        run: cd pure1 && go test -v ./...
